version: "3"
services:
  haproxy:
    image: bineesh13487/nodejsproxy
    ports:
      - "32760:80"
  nodejs:
    image: bineesh13487/nodejs
    ports:
      - "32768:5000"
    depends_on:
      - haproxy
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
